"""Streamlit dashboard for comparing the 5 trained classifiers."""

import pathlib
import io

import joblib
import numpy as np
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import (
    accuracy_score, roc_auc_score, precision_score,
    recall_score, f1_score, matthews_corrcoef,
    confusion_matrix, classification_report,
)

BASE_DIR = pathlib.Path(__file__).parent
MODEL_DIR = BASE_DIR / "models"

MODEL_FILES = {
    "Logistic Regression": "logistic_regression",
    "Decision Tree": "decision_tree",
    "K-Nearest Neighbor (kNN)": "knn",
    "Naive Bayes": "naive_bayes",
    "Random Forest (Ensemble)": "random_forest",
}
LABEL_COL = "y"


@st.cache_resource(show_spinner="Loading models...")
def load_trained_models():
    trained_models = {}
    for label, key in MODEL_FILES.items():
        pkl = MODEL_DIR / f"{key}.pkl"
        if pkl.exists():
            trained_models[label] = joblib.load(pkl)
    return trained_models


def score_predictions(clf, features, actual_y):
    predicted_y = clf.predict(features)
    has_proba = hasattr(clf, "predict_proba")
    proba = clf.predict_proba(features)[:, 1] if has_proba else None
    auc = roc_auc_score(actual_y, proba) if proba is not None else float("nan")
    return {
        "Accuracy":  round(accuracy_score(actual_y, predicted_y), 4),
        "AUC":       round(auc, 4),
        "Precision": round(precision_score(actual_y, predicted_y, zero_division=0), 4),
        "Recall":    round(recall_score(actual_y, predicted_y, zero_division=0), 4),
        "F1":        round(f1_score(actual_y, predicted_y, zero_division=0), 4),
        "MCC":       round(matthews_corrcoef(actual_y, predicted_y), 4),
    }, predicted_y


def draw_confusion_matrix(actual_y, predicted_y, model_name: str):
    cm = confusion_matrix(actual_y, predicted_y)
    fig, ax = plt.subplots(figsize=(4, 3))
    sns.heatmap(
        cm, annot=True, fmt="d", cmap="Blues",
        xticklabels=["No (0)", "Yes (1)"],
        yticklabels=["No (0)", "Yes (1)"],
        ax=ax,
    )
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")
    ax.set_title(f"Confusion Matrix - {model_name}")
    fig.tight_layout()
    return fig


st.set_page_config(
    page_title="Bank Marketing - ML Classifier Dashboard",
    layout="wide",
)

st.title("Bank Marketing - ML Classifier Dashboard")
st.markdown(
    """
    **Dataset:** [UCI Bank Marketing](https://archive.ics.uci.edu/ml/datasets/Bank+Marketing),
    predicts whether a client will subscribe to a term deposit (binary: yes/no).
    **Features:** 19 input features (after dropping `duration`) · **Instances:** 41,188
    """
)

st.sidebar.header("Controls")

uploaded_file = st.sidebar.file_uploader(
    "Upload test CSV (must match test_data.csv schema)",
    type=["csv"],
    help="Upload the test_data.csv generated by training/train_all.ipynb. "
         "Streamlit free tier has limited capacity, so upload only test data.",
)

menu_options = ["All Models"] + list(MODEL_FILES.keys())
chosen_model = st.sidebar.selectbox("Select Model", menu_options)

st.sidebar.markdown("---")
st.sidebar.markdown(
    "**Column order expected:**  \n"
    "`age, campaign, pdays, previous, emp.var.rate, cons.price.idx, "
    "cons.conf.idx, euribor3m, nr.employed, job, marital, education, "
    "default, housing, loan, contact, month, day_of_week, poutcome, y`"
)

if uploaded_file is not None:
    data_df = pd.read_csv(uploaded_file)
    st.sidebar.success(f"Loaded uploaded file ({len(data_df)} rows)")
else:
    default_csv = BASE_DIR / "test_data.csv"
    if default_csv.exists():
        data_df = pd.read_csv(default_csv)
        st.sidebar.info(f"Using bundled test_data.csv ({len(data_df)} rows)")
    else:
        st.error(
            "No test data found. Run `training/train_all.ipynb` to generate "
            "test_data.csv, or upload a CSV file."
        )
        st.stop()

if LABEL_COL not in data_df.columns:
    st.error(f"CSV must contain a `{LABEL_COL}` column (0/1).")
    st.stop()

features = data_df.drop(columns=[LABEL_COL]).values
actual_y = data_df[LABEL_COL].values

trained_models = load_trained_models()
if not trained_models:
    st.error(
        "No trained models found in `models/`. "
        "Run `training/train_all.ipynb` first."
    )
    st.stop()

if chosen_model == "All Models":
    st.subheader("Model Comparison Table")
    table_rows = []
    for label, clf in trained_models.items():
        scores, _ = score_predictions(clf, features, actual_y)
        table_rows.append({"ML Model": label, **scores})
    summary_df = pd.DataFrame(table_rows).set_index("ML Model")
    st.dataframe(summary_df.style.highlight_max(axis=0, color="#d4edda").format("{:.4f}"))

    st.subheader("Accuracy Comparison")
    fig, ax = plt.subplots(figsize=(8, 3))
    ax.barh(summary_df.index, summary_df["Accuracy"], color=sns.color_palette("Blues_d", len(summary_df)))
    ax.set_xlabel("Accuracy")
    ax.set_xlim(0, 1)
    for i, v in enumerate(summary_df["Accuracy"]):
        ax.text(v + 0.005, i, f"{v:.4f}", va="center")
    fig.tight_layout()
    st.pyplot(fig)
    plt.close(fig)

else:
    if chosen_model not in trained_models:
        st.warning(f"Model `{chosen_model}` not found in models/.")
        st.stop()

    clf = trained_models[chosen_model]
    scores, predicted_y = score_predictions(clf, features, actual_y)

    st.subheader(f"{chosen_model} - Evaluation Metrics")
    metric_cols = st.columns(6)
    label_list = list(scores.keys())
    for col, label in zip(metric_cols, label_list):
        col.metric(label, f"{scores[label]:.4f}")

    left_col, right_col = st.columns([1, 1])

    with left_col:
        st.subheader("Confusion Matrix")
        fig = draw_confusion_matrix(actual_y, predicted_y, chosen_model)
        st.pyplot(fig)
        plt.close(fig)

    with right_col:
        st.subheader("Classification Report")
        class_report = classification_report(actual_y, predicted_y, target_names=["No (0)", "Yes (1)"])
        st.code(class_report, language="text")

    st.subheader("All Models - Quick Comparison")
    table_rows = []
    for label, other_clf in trained_models.items():
        scores, _ = score_predictions(other_clf, features, actual_y)
        table_rows.append({"ML Model": label, **scores})
    summary_df = pd.DataFrame(table_rows).set_index("ML Model")
    st.dataframe(summary_df.style.highlight_max(axis=0, color="#d4edda").format("{:.4f}"))
